### ISSUE TITLE
Compatible postgrest-0.4.1.0. release

### ISSUE THREAD

**Issue by PierreR** [diogob/postgrest-ws#12]
The current release will not built with the latest postgrest-0.4.1.0:

https://hydra.nixos.org/build/52420518/nixlog/18

Would you mind making a new release that would be compatible with it ?

I can PR the necessary changes if you wish so.

**Comment by PierreR** [comment]
@diogob I still need you to bump a version on hackage if you don't mind. ;-)

**Comment by diogob** [comment]
Don't mind one bit :D 
I'll do this tonight.

**Comment by diogob** [comment]
Uploaded to hackage 🍻
