### ISSUE TITLE
configurator deps mismatched with postgrest

### ISSUE THREAD

**Issue by PierreR** [diogob/postgrest-ws#22]
Would you be open to change the deps from `configurator` to `configurator-ng` to match the latest version of `postgrest` ?

Cheers

**Comment by PierreR** [comment]
As a note I am not so sure this is a good idea because `configurator` is in stackage while `configurator-ng` is not ...

**Comment by PierreR** [comment]
Well I would argue it is probably a bad idea ...

**Comment by diogob** [comment]
The dependency is in the executable, so to use it as a middleware with postgrest this should not cause any problems.

**Comment by PierreR** [comment]
By the way where is the help for such an usage (as a middleware)

**Comment by diogob** [comment]
Unfortunately there is no documentation for it yet. You can check the middleware call in the sample server here: https://github.com/diogob/postgrest-ws/blob/master/app/Main.hs#L60

**Comment by PierreR** [comment]
Thanks.

I guess I need to 'repackaged' postgrest after patching it (adding the postgrest-ws middleware) or is there another cleaner way ?

**Comment by diogob** [comment]
@PierreR that's it for now. 

Having said that I still need to update the JWT library to use the same one on postgrest-ws and retain full compatibility with the tokens. That should be simple and I will have some time to work on it by the end of the month.
If you make a version that composes both middlewares please let me know so I can link in the README.

**Comment by diogob** [comment]
@PierreR I just opened #24 to keep track of the new JWT implementation.
