### ISSUE TITLE
Support asymmetric JWK (update to jose to keep compatibility with PostgREST tokens)

### ISSUE THREAD

**Issue by diogob** [diogob/postgrest-ws#24]
This PR https://github.com/begriffs/postgrest/pull/919 should be ported to the postgrest-ws claim decoding functions. This means supporting the [jose](https://hackage.haskell.org/package/jose) library

**Comment by PierreR** [comment]
By the way, it would be nice to support/update to  `jose-0.6` in postgrest. I am actually trying to see how to do that but I know nothing about that library so it is a bit of a pain.

**Comment by PierreR** [comment]
Here is the attempt ;-) https://github.com/begriffs/postgrest/pull/997

**Comment by PierreR** [comment]
I have just realized I need to wait for this issue to be solved to go forward ;-)

Do you need some help to achieve this ?

**Comment by PierreR** [comment]
I am also wondering about `audit-channel`. Is this something specific to postgrest-ws and related to 'LISTEN/NOTIFY` ?

**Comment by diogob** [comment]
Hi there, unfortunately I'm on vacation and I won't be able to fix this
issue for the next two weeks 😕

**Comment by diogob** [comment]
Audit-channel is just an arbitrary name to allow a backend app to persist
all exchanged messages. It makes the code of the backend app much simpler
since it does not need to find out the name of active channels.

**Comment by PierreR** [comment]
My attempt to fix this issue with PR #29. Thanks for reviewing it.
