### ISSUE TITLE
JWT that can read all channels

### ISSUE THREAD

**Issue by ebekebe** [diogob/postgrest-ws#27]
From the readme I understand that a JWT needs to include a complete list of all channels one wants to listen to. Is there a way to have a general JWT that can read all channels without listing them explicitly?

The idea is that we have a service that listens to channels that are created at runtime. The service is configured with a single fixed JWT and we don't want to fetch a new JWT for every channel we want to listen to. The channels don't include any payload, so there is no need for advanced security. Also, the list of all possible channel names is too long to include in a JWT.

Any of the following options would work for us:
1. Have a single master JWT `{"mode": "ra"}` (r - read, a - all)
1. Allow substring or regex matching: `{"mode": "r","channelExpr": ".*"}`
1. Disable write access in the config

I would be happy to get some help on this.

**Edit:**
In case this wan't clear: We need to restrict the service to only read channels. Write access must be disabled.

**Comment by diogob** [comment]
@ebekebe there is a feature like this implemented but still undocumented. Is a option called `audit-channel`. When the option `audit-channel` is present in the config, all messages sent will be written to that channel as well as the original recipient. You can check the code that does this here: https://github.com/diogob/postgrest-ws/blob/master/src/PostgRESTWS.hs#L77

I'll update the docs as soon as I'm back from vacations ;)

**Comment by ebekebe** [comment]
@diogob Thanks for your help. From what I understand, the `audit-channel` will be a single channel. So all clients will receive all messages. This would work in principle, but flood the network with unnecessary messages. I was rather looking for a solution where I can still subscribe to a subset of messages. I see now, that title was misleading.

So let me explain a little better. When I asked to disable write access in the config, I had a scenario in mind where every client knows the JWT secret and can generate its own JWT. If write access from clients was disabled, clients could only subscribe to events where they know the channel name and are unable to flood the system with junk messages on random channels.
This solution is still not optimal, since clients must carry the complexity of generating JWTs. This is of course not the most complicated thing to do, but still adds overhead and I like to keep things as simple as they can be. (But it would work for us.)

What I would love to see is a way to pass a JWT and the channel name separately. For instance the url `/:channel/:jwt` should work. With such a setup, we could use the same JWT for postgrest-ws and normal postgrest endpoints, which reduces complexity.
I understand that this might be a bigger change that is not quickly accomplished. I can work with `audit-channel` for now, but still like to discuss this feature request.

**Comment by diogob** [comment]
I like the idea of having the JWT and the channel as orthogonal elements in the URI. Also making it friendlier to integrate with postgrest URIs is a nice property. I'll make a feature proposal on this thread and we can work on it from there

**Comment by diogob** [comment]
@ebekebe I'm having some trouble understanding a use case where clients have access to the JWT secret but cannot write to channels.
By definition, whoever has the secret, can sign any sort of payload, therefore any mode could be specified (even invalid ones).

Besides, having a configuration that changes how the tokens are interpreted introduces more complexity in the form of additional error handling.

Wouldn't it be simpler to require clients to request a token from a service, and have that service emit tokens only for reading?

I was thinking of allowing the `/:channel/:jwt` URI as long as the payload in the JWT does not contain a channel. So the payload for a master read-only token would be `{"mode": "r"}`.
In cases where the user tries to pass the channel in the URI but using a token that contains a channel the connection would be rejected.

**Comment by ebekebe** [comment]
@diogob When we have `/:channel/:jwt`, there is no use case for clients having the JWT secret from where I am standing. I very much prefer the way you suggested. If you say it is easier to implement, all the better.
