### ISSUE TITLE
How do you access Postgrest's rest API

### ISSUE THREAD

**Issue by simg** [diogob/postgrest-ws#28]
Sorry if I'm missing something obvious, but is the idea that you run a Postgrest server and Postgrest-ws at the same time? 

I don't seem to be able to access the Rest API whilst only running Postgrest-ws

**Comment by PierreR** [comment]
#22 will give you more information on the subject.

**Comment by simg** [comment]
Thanks, but that doesn't really answer my question.

**Comment by PierreR** [comment]
My understanding is that `postgrest-ws` as an executable is a bit of a test bed. If you want to use both, it is better to patch `postgrest` to include the `postgest-ws` middleware and use one executable only.

**Comment by PierreR** [comment]
If you follow #24 from #22 you will see that one current problem is the mismatch between jwt related library. `postgrest-ws` needs to drop the `jwt` package for `jose` (which is a recent postgrest change).

Does it help ?

**Comment by simg** [comment]
Ah Ok, thanks. That's pretty much what I thought, although I'm thinking of using a proxy server to forward http or websockets requests to the appropriate port.

**Comment by PierreR** [comment]
That said if you only want to use `postgrest-ws` (no need for a REST API) I would say it is ok too (but the README seems to contradict that assertion ;-)

**Comment by PierreR** [comment]
I don't know why or if having 2 separate executables is really problematic.  I will let @diogob to answer more precisely on that point.

**Comment by simg** [comment]
having to run 2 executables is more complicated, but I can see advantages to that approach.

**Comment by diogob** [comment]
@simg using two executables should be fine. The postgrest-ws will not give you access to the REST api, only the websockets functionality. The project started as a way to implement websockets in postgrest, but during the merge request we decided to keep them separate. The README and docs still need some love.

@PierreR thanks for jumping in :D
