### ISSUE TITLE
Connection is instantly dropped in read-only mode

### ISSUE THREAD

**Issue by myfreeweb** [diogob/postgrest-ws#5]
Hi, thanks for your project!

Found a bug: you're only doing `forever $ …` in the `when (hasWrite mode)` section. Without it, the listen thread is forked and the function ends after that, instantly disconnecting the client.

**Comment by diogob** [comment]
Because the `listenSession` is an infinite loop. So that should not cause any problems. Do you have a test case that I could use to reproduce the problem?

**Comment by myfreeweb** [comment]
Just try using a JWT with `r` mode, without the write permission, that's the test case.

You run that infinite loop in a `forkIO`. That thread is forked, then the current thread stops because it has nothing else to do, and the connection is instantly dropped because of that.

**Comment by diogob** [comment]
@myfreeweb thanks for the reply, I just realized it now! Marked as a bug, will fix this ASAP
