### ISSUE TITLE
Upgrade to postgrest 0.4

### ISSUE THREAD

**Issue by PierreRochard** [diogob/postgrest-ws#8]
I realized this add-on is a version behind when I tried using a config file instead of command line args. I played around with the stack.yaml and I'm now re-building. I have zero Haskell experience but if this works I'll put in a pull request.

**Comment by diogob** [comment]
Some interfaces have changed from 0.3 to 0.4.
It will require some code changes.

**Comment by PierreRochard** [comment]
Indeed, the build broke. Motivation to learn Haskell! 😃

**Comment by PierreRochard** [comment]
Holy smokes that was fast @diogob! Thank you, I really appreciate this project. 👍

**Comment by diogob** [comment]
@PierreRochard you are welcome, but be aware that this code is still not production quality, see #9 for details. I'll write a note on the README.

**Comment by PierreRochard** [comment]
Thank you for the heads up, I'm using it just for a side project at this point: https://github.com/PierreRochard/primeng-postgrest

I look forward to eventually learning Haskell and contributing back!
